version: "3.8"

services:
  frontstage:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backstage:
    build:
      context: ./frontend-backstage
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./frontend-backstage:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    environment:
      - CI_ENVIRONMENT=development
      - DB_HOST=db
      - DB_USER=devuser
      - DB_PASSWORD=devpass
      - DB_NAME=shopping

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=shopping
      - MYSQL_USER=devuser
      - MYSQL_PASSWORD=devpass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
